version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=${CONFIGURATION:production}
    container_name: angular-docker
    image: dz/angular-docker
    restart: unless-stopped
    ports:
      - "${PORT}:80"